
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29

             

              version: "3"
             

             

              services:
             

             

              database:
             

             

              image: mysql
             

             

              restart: always
             

             

              environment:
             

             

              MYSQL_ROOT_PASSWORD: wppassword
             

             

              MYSQL_DATABASE: wpdb
             

             

              MYSQL_USER: wpuser
             

             

              MYSQL_PASSWORD: wppassword
             

             

              volumes:
             

             

              - mysql:/var/lib/mysql
             

             

               
             

             

              wordpress:
             

             

              depends_on:
             

             

              - database
             

             

              image: wordpress:latest
             

             

              restart: always
             

             

              ports:
             

             

              - "8021:80"
             

             

              environment:
             

             

              WORDPRESS_DB_HOST: database:3306
             

             

              WORDPRESS_DB_USER: wpuser
             

             

              WORDPRESS_DB_PASSWORD: wppassword
             

             

              WORDPRESS_DB_NAME: wpdb
             

             

               
             

             

              volumes:
             

             

              ["./:/var/www/html"]
             

             

              volumes:
